# permissions for end users to view openstackcloudconfigurationprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackcloudconfigurationprofile-viewer-role
rules:
- apiGroups:
  - cluster.kupenstack.io
  resources:
  - openstackcloudconfigurationprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.kupenstack.io
  resources:
  - openstackcloudconfigurationprofiles/status
  verbs:
  - get
