# permissions for end users to view openstacknodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstacknode-viewer-role
rules:
- apiGroups:
  - cluster.kupenstack.io
  resources:
  - openstacknodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cluster.kupenstack.io
  resources:
  - openstacknodes/status
  verbs:
  - get
