# permissions for end users to edit openstacknodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstacknode-editor-role
rules:
- apiGroups:
  - cluster.kupenstack.io
  resources:
  - openstacknodes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.kupenstack.io
  resources:
  - openstacknodes/status
  verbs:
  - get
