# permissions for end users to edit openstackcloudconfigurationprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openstackcloudconfigurationprofile-editor-role
rules:
- apiGroups:
  - cluster.kupenstack.io
  resources:
  - openstackcloudconfigurationprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.kupenstack.io
  resources:
  - openstackcloudconfigurationprofiles/status
  verbs:
  - get
