---
apiVersion: v1
kind: Namespace
metadata:
  name: kupenstack

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kupenstack-controller
  namespace: kupenstack
  labels:
    controller-manager: kupenstack
spec:
  replicas: 1
  selector:
      matchLabels:
          controller-manager: kupenstack
  template:
    metadata:
      labels:
        controller-manager: kupenstack
    spec:
      containers:
      - name: manager
        command:
        - /manager
        args:
        - --leader-elect
        - --kupenstack-configuration-file
        - /etc/kupenstack/config.yaml
        imagePullPolicy: Always
        image: parthyadav/kupenstack-controller:demo-2
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
          - name: config-volume
            mountPath: /etc/kupenstack
      serviceAccountName: kupenstack-admin
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: kupenstack-config

        
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kupenstack-admin
subjects:
- kind: ServiceAccount
  name: kupenstack-admin
  namespace: kupenstack
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kupenstack-admin
  namespace: kupenstack

---
kind: Service
apiVersion: v1
metadata:
  name: horizon-nodeport
  namespace: kupenstack
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 32020
  selector:
    application: horizon
    component: server




